# by SocialMoods

# _________             .__       .__      _____                    .___
# /   _____/ ____   ____ |__|____  |  |    /     \   ____   ____   __| _/______
# \_____  \ /  _ \_/ ___\|  \__  \ |  |   /  \ /  \ /  _ \ /  _ \ / __ |/  ___/
# /        (  <_> )  \___|  |/ __ \|  |__/    Y    (  <_> |  <_> ) /_/ |\___ \
# /_______  /\____/ \___  >__(____  /____/\____|__  /\____/ \____/\____ /____  >
# \/            \/        \/              \/                   \/    \/

# Спиздил или слил плагин - пидорас.


# Предметы добавляются по форме ниже

# "номер":
#   itemId: <ID предмета>
#   count: <количество>
#   price: <цена>
#   url: <url-ссылка на изображение>
#

# Коэффицент увеличения стоимости ставится только в виде Double - числом с плавающей точкой. 1% = 0.01, 100% = 1.0, 101% = 1.01
# Значение отвечает за колибание цен взависимости от количества продаж за час
price-ratio: 0.2
# Коэффицент увеличения стоимости в зависимости от уровня ставится только в виде Double - числом с плавающей точкой. 1% = 0.01, 100% = 1.0, 101% = 1.01
# Значение отвечает на увеличение цены в зависимости от уровня скупщика
level-ratio: 0.1
# Время в минутах через которое сбрасывается счетчик количества продаж для изменения цен
update-period: 60
# Сообщения об обновлении цен на скупщика
update-mesage: "Скупщик был обновлен!"
# Popup-сообщение о покупке предмета в авто-скупщике
sale-popup: "Вы продали {item_name} за {amount} монет!"

# Настройка формы
buyer-form:
  title: "§l§aСкупщик"
  content: |
    Добро пожаловать к §aскупщику!§r§f
    Для продажи предмет должен быть в инвентаре
  button-template: "{item_name} за §a{price}монет/шт§r§f"
  tutorial-title: "§l§aТуториал"
  item-form-content: |
    Вы собираетесь продать §a{item}§r§f
    За §a{price}/шт§r§f
    
    У вас есть: §a{available}§r§f
  tutorial-content: |
    Скупщик работает в зависимости от динамики §aпродажи§r§f.§r§f
    
    Если продажи §aмаленькие§r§f - цена возрастает!
    Если продажи §aбольшие§r§f - цена убывает!
    
    §aКоэффицент§r§f цены отвечает за рамки изменения цены в зависимости от продаж.
    Его значение сейчас: §a{ratio}%§r§f
  tutorial-button: "Информация и настройки"
  messages:
    not-enough-items: "У вас недостаточно предметов для продажи!"
    success: "Вы успешно продали предметы! {count}"

# Форма с нгастройками
settings-form:
  title: "§l§aНастройки"
  status-label: |
    §aАвто-скупщик§r§f делает скупку удобнее!§r§f
    
    Просто добудьте §aресурс§r§f, §aавтоматически§r§f купит все предметы!
    
    §aПримечание:§r§f Авто-скупщик работает только на предметах из основного меню.
    
    Статус: §a{status}§r§f
  toggle-label: "Включить/отключить авто-скупщика"
  messages:
    enabled: "Авто-скупщик включен"
    disabled: "Авто-скупщик отключен"

# АВТО-СКУПЩИК НЕ РАБОТАЕТ НА РЕСУРСЫ НАПРИМЕР НЕОБРАБОТАННОЕ ЖЕЛЕЗО ИТД!
# Настройка предметов
"0":
  itemId: 265 # Железный слиток
  count: 15
  price: 100
  url: "https://static.wikia.nocookie.net/minecraft_ru_gamepedia/images/0/0a/%D0%96%D0%B5%D0%BB%D0%B5%D0%B7%D0%BD%D1%8B%D0%B9_%D1%81%D0%BB%D0%B8%D1%82%D0%BE%D0%BA_JE3_BE2.png/revision/latest?cb=20190424161840"

"1":
  itemId: 266 # Золотой слиток
  count: 10
  price: 200
  url: "https://static.wikia.nocookie.net/minecraft_ru_gamepedia/images/6/67/%D0%97%D0%BE%D0%BB%D0%BE%D1%82%D0%BE%D0%B9_%D1%81%D0%BB%D0%B8%D1%82%D0%BE%D0%BA_JE1.png/revision/latest?cb=20201014092252"

"2":
  itemId: 264 # Алмаз
  count: 5
  price: 500
  url: "https://static.wikia.nocookie.net/minecraft_ru_gamepedia/images/a/a9/%D0%90%D0%BB%D0%BC%D0%B0%D0%B7_JE2_BE2.png/revision/latest?cb=20180801080506"


