# by SocialMoods and ForgePlugins Studio

# Предметы добавляются по форме ниже

# "номер":
#   itemId: <ID предмета>
#   count: <количество>
#   price: <цена>
#   url: <url-ссылка на изображение>
#

# Коэффицент увеличения стоимости ставится только в виде Double - числом с плавающей точкой. 1% = 0.01, 100% = 1.0, 101% = 1.01
# Значение отвечает за колибание цен взависимости от количества продаж за час
price-ratio: 0.2
# Коэффицент увеличения стоимости в зависимости от уровня ставится только в виде Double - числом с плавающей точкой. 1% = 0.01, 100% = 1.0, 101% = 1.01
# Значение отвечает на увеличение цены в зависимости от уровня скупщика
level-ratio: 0.1
# Время в минутах через которое сбрасывается счетчик количества продаж для изменения цен
update-period: 60
# Сообщения об обновлении цен на скупщика
update-mesage: "Скупщик был обновлен!"
# Popup-сообщение о покупке предмета в авто-скупщике
sale-popup: "Вы продали {item_name} за {amount} монет!"

# Настройка авто-скупщика
auto-buyer:
  # Включить/отключить поддержку ресурсов (необработанное железо, золото и т.д.)
  resources-enabled: true
  # Словарь ресурсов и их продуктов (ID ресурса: ID продукта)
  resources:
    "15": 265  # Железная руда -> Железный слиток
    "14": 266  # Золотая руда -> Золотой слиток
    "56": 264  # Алмазная руда -> Алмаз
    "129": 388 # Изумрудная руда -> Изумруд
    "153": 406 # Кварцевая руда -> Кварц

# Настройка формы
buyer-form:
  title: "§l§aСкупщик"
  content: |
    Добро пожаловать к §aскупщику!§r§f
    Для продажи предмет должен быть в инвентаре
  button-template: "{item_name} за §a{price}монет/шт§r§f"
  tutorial-title: "§l§aТуториал"
  item-form-content: |
    Вы собираетесь продать §a{item}§r§f
    За §a{price}/шт§r§f
    
    У вас есть: §a{available}§r§f
  tutorial-content: |
    Скупщик работает в зависимости от динамики §aпродажи§r§f.§r§f
    
    Если продажи §aмаленькие§r§f - цена возрастает!
    Если продажи §aбольшие§r§f - цена убывает!
    
    §aКоэффицент§r§f цены отвечает за рамки изменения цены в зависимости от продаж.
    Его значение сейчас: §a{ratio}%§r§f
  tutorial-button: "Информация и настройки"
  messages:
    not-enough-items: "У вас недостаточно предметов для продажи!"
    success: "Вы успешно продали предметы! {count}"

# Форма с нгастройками
settings-form:
  title: "§l§aНастройки"
  status-label: |
    §aАвто-скупщик§r§f делает скупку удобнее!§r§f
    
    Просто добудьте §aресурс§r§f, §aавтоматически§r§f купит все предметы!
    
    §aПримечание:§r§f Авто-скупщик работает на предметах из основного меню и на ресурсах.
    
    Статус: §a{status}§r§f
  toggle-label: "Включить/отключить авто-скупщика"
  messages:
    enabled: "Авто-скупщик включен"
    disabled: "Авто-скупщик отключен"

# Настройка предметов
"0":
  itemId: 265 # Железный слиток
  count: 15
  price: 100
  url: "textures/items/iron_ingot"

"1":
  itemId: 266 # Золотой слиток
  count: 10
  price: 200
  url: "textures/items/gold_ingot"

"2":
  itemId: 264 # Алмаз
  count: 5
  price: 500
  url: "textures/items/diamond"


